modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="prunus"
version="1.0.0"
displayName="Prunus"
description='''
Personal Pocket Dimensions
'''

[[dependencies.prunus]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.prunus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
